#!/usr/bin/env bash
#This script is displaying "Best School" 10 times too

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 3 ]
	then
		echo "Bad luck"
	elif [ $count -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done
