#!/usr/bin/env bash
#This script is displaying numbers from 1 to 20
#print additional info for specific iterations

count=1

while [ $count -le 20 ]
do
	case $count in
		4)
			echo "4"
			echo "bad luck from china"
			;;
		7)
			echo "7"
			echo "bad luck from Japan"
			;;
		17)
			echo "17"
			echo "bad luck from Italy"
			;;
		*)
			echo "$count"
			;;
	esac
	((count++))

done
